services:
  todo-app:
    build:
      context: .
    ports:
      - "3000:80"
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_secret
      MYSQL_DATABASE: notes_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql
      - ./dump/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

volumes:
  mysql-data: